# Generated by Django 5.1.5 on 2025-02-20 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_transaction_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('cars', 'Автомобиль'), ('food', 'Продукты'), ('rent', 'Аренда'), ('salary', 'Зарплата'), ('entertainment', 'Развлечения')], default='default_value', max_length=20),
            preserve_default=False,
        ),
    ]
