# Generated by Django 5.1.5 on 2025-02-21 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_transaction_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='category',
            field=models.CharField(choices=[('cars', 'Автомобиль'), ('food', 'Продукты'), ('rent', 'Аренда'), ('salary', 'Зарплата'), ('entertainment', 'Развлечения')], max_length=20),
        ),
    ]
